# Generated by Django 4.2.8 on 2025-03-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("medium", models.CharField(max_length=100)),
                ("date_created", models.DateField(blank=True)),
                (
                    "collection",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Inktober 2019", "Inktober2019"),
                            ("Inktober 2020", "Inktober2020"),
                            ("Inktober 2022", "Inktober2022"),
                            ("Inktober 2023", "Inktober2023"),
                            ("Inktober 2024", "Inktober2024"),
                            ("Portraits", "Portraits"),
                        ],
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(upload_to="artwork_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
